### ISSUE TITLE
Is there a way to prevent spaces between consecutive capital letters?

### ISSUE THREAD

**Issue by visarts** [jdpedrie/angularjs-camelCase-to-human-filter#5]
So if I have a string, camelCaseToHUMAN, is there a way to modify the JS file, so that it would print, Camel Case To HUMAN ?

**Comment by jdpedrie** [comment]
I think you'll need to figure out another way to transform that string, because ignoring multiple caps next to each other would break any string with 1-letter words, e.g. `thisIsAString`. That seems to be a much more common case than yours, unfortunately.

Let me know if you have any thoughts on ways to get around that issue!
